import React, { useEffect, useState } from 'react';
import type { Client } from '@/lib/data';

export function InvoicePDF({ invoice }: { invoice: any }) {
  const [client, setClient] = useState<Client | undefined>(undefined);

  useEffect(() => {
    let mounted = true;
    if (invoice.clientId) {
      (async () => {
        try {
          const res = await fetch(`/api/clients/${invoice.clientId}`);
          if (!mounted) return;
          if (res.ok) setClient(await res.json());
        } catch (e) { /* ignore */ }
      })();
    }
    return () => { mounted = false; };
  }, [invoice.clientId]);

  const date = new Date(invoice.createdAt || Date.now()).toLocaleDateString();

  return (
    <div style={{ fontFamily: 'sans-serif', padding: 20, color: '#000', width: 700 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #000', paddingBottom: 12 }}>
        <div>
          <h1 style={{ fontSize: 28, fontWeight: 'bold', margin: 0 }}>INVOICE</h1>
          <p style={{ margin: '6px 0 0 0' }}>Pixelate Nest</p>
          <p style={{ margin: '2px 0 0 0' }}>Invoice generated by Pixelate Nest CRM</p>
        </div>
        <div style={{ textAlign: 'right' }}>
          <p style={{ margin: 0 }}><strong>Invoice ID:</strong> {invoice.id ?? (invoice._id ?? '')}</p>
          <p style={{ margin: 0 }}><strong>Date:</strong> {date}</p>
          <p style={{ margin: 0 }}><strong>Due:</strong> {invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : ''}</p>
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 20 }}>
        <div>
          <h3 style={{ margin: 0 }}>Billed To</h3>
          <p style={{ margin: '6px 0 0 0' }}>{client ? client.name : invoice.clientName || 'Client'}</p>
          {client && (
            <p style={{ margin: '6px 0 0 0' }}>{client.email} | {client.phone}</p>
          )}
        </div>
        <div style={{ textAlign: 'right' }}>
          <h3 style={{ margin: 0 }}>/</h3>
        </div>
      </div>

      <div style={{ marginTop: 20 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ backgroundColor: '#f3f3f3' }}>
              <th style={{ border: '1px solid #ddd', padding: 8, textAlign: 'left' }}>Description</th>
              <th style={{ border: '1px solid #ddd', padding: 8, width: 120, textAlign: 'right' }}>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ border: '1px solid #ddd', padding: 8 }}>{invoice.title || invoice.projectTitle || 'Project work'}</td>
              <td style={{ border: '1px solid #ddd', padding: 8, textAlign: 'right' }}>₹{Number(invoice.amount || 0).toLocaleString()}</td>
            </tr>
          </tbody>
        </table>

        <div style={{ marginTop: 20, display: 'flex', justifyContent: 'flex-end' }}>
          <div style={{ width: 240 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 16 }}>
              <span>Subtotal</span>
              <span>₹{Number(invoice.amount || 0).toLocaleString()}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8, fontWeight: 'bold', fontSize: 18 }}>
              <span>Total</span>
              <span>₹{Number(invoice.amount || 0).toLocaleString()}</span>
            </div>
          </div>
        </div>
      </div>

      <div style={{ marginTop: 40, fontSize: 12, color: '#666' }}>
        <p>Payment due within 30 days. Please contact us for any questions regarding this invoice.</p>
      </div>
    </div>
  );
}
